POST http://localhost:3001/notes
content-type: application/json

{
    "title": "title",
    "userID": "5c2a2363ace90a2690a157b2",
    "content": "New note",
    "important": true,
    "date": "Wed, 21 Oct 2015 18:27:50 GMT"
}